#!/usr/bin/env python
"""
    This module consists of functions dealing with collection and processing of
    data files generated during e-by-e calculations into databases.

    ***** eccentricity *****:
    This table has the format:
    event_id (int), harmonic_order (smallint), ecc_real (double), ecc_imag (double)

"""

from os import path
from sys import argv, exit
from DBR import SqliteDB

import numpy as np


amount_of_feedback = 99 # number of printed lines on the terminal

# declare default parameters
# all the particles that can be collected
default_particle_names=[
    "thermal_211", "thermal_321", "thermal_2212",
    'pion_p', 'Kaon_p', 'proton', 'Lambda', 'Sigma_p', 'Sigma_m', 'Omega', 'Xi_m',
    'Charged', 'Charged_ptcut02', 'Charged_ptcut03', 'Charged_ptcut05', # for dN/dy
    'R_0.5_Charged_eta', 'R_2.5_Charged_eta', 'R_2.0_Charged_eta', 'R_0.5_2.5_Charged_eta', 'R_0.5_4.8_Charged_eta',
    'R_0.5_Charged_ptcut02_eta', 'R_2.5_Charged_ptcut02_eta', 'R_2.0_Charged_ptcut02_eta', 'R_0.5_2.5_Charged_ptcut02_eta', 'R_0.5_4.8_Charged_ptcut02_eta',
    'R_0.5_Charged_ptcut05_eta', 'R_2.5_Charged_ptcut05_eta', 'R_2.0_Charged_ptcut05_eta', 'R_0.5_2.5_Charged_ptcut05_eta', 'R_0.5_4.8_Charged_ptcut05_eta',
    'R_0.5_Charged_ptcut03_eta', 'R_2.5_Charged_ptcut03_eta', 'R_2.0_Charged_ptcut03_eta', 'R_0.5_2.5_Charged_ptcut03_eta', 'R_0.5_4.8_Charged_ptcut03_eta',
    'R_0.5_Charged_ptcut03_3_eta', 'R_2.5_Charged_ptcut03_3_eta', 'R_2.0_Charged_ptcut03_3_eta', 'R_0.5_2.5_Charged_ptcut03_3_eta', 'R_0.5_4.8_Charged_ptcut03_3_eta',
    ]

# what name to save as (11P5N)
default_save_as_abr="11P5N_moments_order_%%d_%s.dat"

# flow and differential flow files (6InteFlow, 3P3NDiffFlow)
# use new format: both thermal and RD particles share the same pattern. Use extractThermal3 script from iS with version >= 1.2.1.9 to ensure this.
default_vn_file_path_abr="spectra/%s_integrated_vndata.dat"
default_diff_vn_file_path_abr="spectra/%s_vndata.dat"
# for backward compatibility
default_historical_thermal_vn_file_path_abr="spectra/%s_integrated_vn.dat"
default_historical_thermal_diff_vn_file_path_abr="spectra/%s_vn.dat"

# "conventional" eccentricity files (6Ecc)
default_sn_file_path="results/ecc-init-sd.dat"
default_en_file_path="results/ecc-init.dat"

# r-power eccentricity files (3Ecc, 3Ecc, 2NP1Ecc, 2NP1Ecc)
# these exotic eccentriciy files are only generated by VISHNew with version>=1.10.0
default_rp_sn_file_path='results/ecc-init-sd-r_power-%d.dat' # for r-power exotic ecc files from ebe folder; using sd
default_rp_en_file_path='results/ecc-init-r_power-%d.dat' # using ed
default_save_rp_sn_as='sd_ecc_r_power_%d.dat' # using what names to save exotic sd ecc files
default_save_rp_en_as='ed_ecc_r_power_%d.dat' # using what names to save exotic ed ecc files
default_r_power_start_with=0 # for backward compatibility use 1


class EbeCollector:
    pass



#------------------------------------------------------------------------------
if __name__ == "__main__":
    print("----------------------------------------------------")
    print("Welcome! -- Zhi Qiu")
    print("----------------------------------------------------")
    if len(argv) == 1:
        print("Use one of the following:\n")
        print("See the source file.")
    else:
        print("Executing: "+argv[1]+"('"+"','".join(argv[2:])+"')\n")
        exec(argv[1]+"('"+"','".join(argv[2:])+"')")
