#! /usr/bin/env bash

if [ $# -lt 1 ]
then
	echo "Usage: agr2PS list-of-agr-files"
	exit
fi

while [ $# -gt 0 ]
do
        file=`echo "$1" | sed 's/ /\?/g'`
	filename=$(basename $file)
        grace $file -printfile ${filename%.*}.ps -hardcopy
        shift
done
