#! /usr/bin/env bash

# Flow anisotropy only:
./generateGraceBatchFile.py generatePlotFile '[["anisotropy.dat",1,4,"\\x e\\s\\f{}p\\N \\f{}"]]' '"epsilonP.bat"' '"Flow momentum anisotropy"' '"\\x t \\f{}-\\x t \\f{}0 (fm/c)"' '"\\x e\\s\\f{}p\\N \\f{}"' '[]' '[]' "$2"
# Total anisotropy:
./generateGraceBatchFile.py generatePlotFile '[["anisotropy.dat",1,5,"\\x e\\s\\f{}p\\S,\\N \\f{}"]]' '"epsilonPPrime.bat"' '"Total momentum anisotropy"' '"\\x t \\f{}-\\x t \\f{}\\s0\\N (fm/c)"' '"\\x e\\s\\f{}p\\S,\\N\\N \\f{}"' '[]' '[]' "$2"

if [ $# -gt 0 ] # generate scaled .bat only knowing what scaling parameters are
then
  ./generateGraceBatchFile.py generatePlotFile '[["anisotropy.dat","($1/ttau0%d+1):($4)","\\x e\\s\\f{}p\\N \\f{}"]]' '"epsilonP-scaled.bat"' '"Scaled flow momentum anisotropy"' '"\\x t \\f{}/\\x t\\s0\\N \\f{}"' '"\\x e\\s\\f{}p\\N \\f{}"' "$1" '[]' "$2"
  ./generateGraceBatchFile.py generatePlotFile '[["anisotropy.dat","($1/ttau0%d+1):($5)","\\x e\\s\\f{}p\\S,\\N \\f{}"]]' '"epsilonPPrime-scaled.bat"' '"Scaled total momentum anisotropy"' '"\\x t \\f{}/\\x t\\s0\\N \\f{}"' '"\\x e\\s\\f{}p\\S,\\N\\N \\f{}"' "$1" '[]' "$2"
fi
