#! /usr/bin/env bash

# First those without PiTrace curves:
./generateGraceBatchFile.py generatePlotFile '[["surface.dat",5,2,"freezeout surface"]]' '"fz.bat"' '"Freezeout surface"' '"r (fm)"' '"\\x t \\f{} (fm/c)"' '[]' '[]' "$2"
# Then those with PiTrace curves:
./generateGraceBatchFile.py generatePlotFile '[["surface.dat",5,2,"freezeout surface"],["PiTrace.dat",2,1,"PiTrace"],["PiTrace.dat",3,1,"PiTrace"],["PiTrace.dat",4,1,"PiTrace"]]' '"fz-withPi.bat"' '"Freezeout surface and PiTrace"' '"r (fm)"' '"\\x t \\f{} (fm/c)"' '[]' '[]' "$2"


if [ $# -gt 0 ] # generate scaled .bat only knowing what scaling parameters are
then
  ./generateGraceBatchFile.py generatePlotFile '[["surface.dat","($5/rrad%d):($2/ttau0%d)","freezeout surface"]]' '"fz-scale.bat"' '"Scaled freezeout surface"' '"r/R"' '"\\x t \\f{}/\\x t\\s0\\N \\f{}"' "$1" "$2"
  ./generateGraceBatchFile.py generatePlotFile '[["surface.dat","($5/rrad%d):($2/ttau0%d)","freezeout surface"],["PiTrace.dat","($2/rrad%d):($1/ttau0%d)","PiTrace"],["PiTrace.dat","($3/rrad%d):($1/ttau0%d)","PiTrace"],["PiTrace.dat","($4/rrad%d):($1/ttau0%d)","PiTrace"]]' '"fz-withPi-scaled.bat"' '"Scaled freezeout surface and PiTrace"' '"r/R"' '"\\x t \\f{}/\\x t\\s0\\N \\f{}"' "$1" '[]' "$2"
fi
